apiVersion: v1
kind: Service
metadata:
  name: moneyball-frontend
  namespace: football-moneyball
spec:
  selector:
    app: moneyball-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
