apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: football-moneyball
type: Opaque
stringData:
  POSTGRES_USER: moneyball
  POSTGRES_PASSWORD: moneyball
  POSTGRES_DB: moneyball
